/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { VideoCall } from "./VideoCall";
import { VideoCallCountArgs } from "./VideoCallCountArgs";
import { VideoCallFindManyArgs } from "./VideoCallFindManyArgs";
import { VideoCallFindUniqueArgs } from "./VideoCallFindUniqueArgs";
import { CreateVideoCallArgs } from "./CreateVideoCallArgs";
import { UpdateVideoCallArgs } from "./UpdateVideoCallArgs";
import { DeleteVideoCallArgs } from "./DeleteVideoCallArgs";
import { VideoCallParticipantFindManyArgs } from "../../videoCallParticipant/base/VideoCallParticipantFindManyArgs";
import { VideoCallParticipant } from "../../videoCallParticipant/base/VideoCallParticipant";
import { VideoCallService } from "../videoCall.service";
@graphql.Resolver(() => VideoCall)
export class VideoCallResolverBase {
  constructor(protected readonly service: VideoCallService) {}

  async _videoCallsMeta(
    @graphql.Args() args: VideoCallCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [VideoCall])
  async videoCalls(
    @graphql.Args() args: VideoCallFindManyArgs
  ): Promise<VideoCall[]> {
    return this.service.videoCalls(args);
  }

  @graphql.Query(() => VideoCall, { nullable: true })
  async videoCall(
    @graphql.Args() args: VideoCallFindUniqueArgs
  ): Promise<VideoCall | null> {
    const result = await this.service.videoCall(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => VideoCall)
  async createVideoCall(
    @graphql.Args() args: CreateVideoCallArgs
  ): Promise<VideoCall> {
    return await this.service.createVideoCall({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => VideoCall)
  async updateVideoCall(
    @graphql.Args() args: UpdateVideoCallArgs
  ): Promise<VideoCall | null> {
    try {
      return await this.service.updateVideoCall({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VideoCall)
  async deleteVideoCall(
    @graphql.Args() args: DeleteVideoCallArgs
  ): Promise<VideoCall | null> {
    try {
      return await this.service.deleteVideoCall(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [VideoCallParticipant], {
    name: "videoCallParticipants",
  })
  async findVideoCallParticipants(
    @graphql.Parent() parent: VideoCall,
    @graphql.Args() args: VideoCallParticipantFindManyArgs
  ): Promise<VideoCallParticipant[]> {
    const results = await this.service.findVideoCallParticipants(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }
}
